# Numpy_Assignment_2::

In [1]:
import numpy as np

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr2d = arr1d.reshape(2,5)
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [4]:
a= np.arange(10).reshape(2,5)
b= np.ones((2,5),dtype='int32')


In [5]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [6]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [7]:
#method1
arr2d.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#method2
arr2d.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [9]:
higher_dim_array = np.arange(15).reshape(3,5)
higher_dim_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
higher_dim_array.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
higher_dim_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [12]:
one_dim_array = np.arange(15)
one_dim_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
one_dim_array.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [14]:
an_array = np.arange(25).reshape(5,5)
an_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
np.square(an_array)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [16]:
an_array1 = np.arange(30).reshape(5,6)
an_array1.mean()

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [17]:
an_array1.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [18]:
np.median(an_array1)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [19]:
an_array1.transpose()

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [20]:
an_array4=np.arange(16).reshape(4,4)
an_array4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
#method 1
sum(np.diagonal(an_array4))

30

In [22]:
#method 2
np.trace(an_array4)

30

## Question:13

### Find the determinant of the previous array in Q12?

In [23]:
determinant  = np.linalg.det(an_array4)
determinant

-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [24]:
ar = np.arange(10).reshape(2,5)
ar

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
np.percentile(ar,5)

0.45

In [26]:
np.percentile(ar,95)

8.549999999999999

## Question:15

### How to find if a given array has any null values?

In [29]:

ar3 = np.array([1,None, 8,9], dtype ='float')
print(ar3)
np.isnan(ar3).any()

[ 1. nan  8.  9.]


True