# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
np.arange(10) * 0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [228]:
np.zeros(10,dtype='int32')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

3. Create a vector with values ranging from 10 to 49

In [8]:
arr1di = np.arange(10,50)
arr1di

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [17]:
np.shape(arr1di)

(40,)

5. Print the type of the previous array in question 3

In [11]:
arr1di.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [13]:
print(np.__version__)
print(np.show_config())

1.15.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/sufi/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/sufi/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/sufi/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', '

7. Print the dimension of the array in question 3


In [14]:
arr1di.ndim

1

8. Create a boolean array with all the True values

In [18]:
np.ones(10,dtype ="bool")

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [20]:
arr2di = np.arange(10).reshape(2,5)
arr2di

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

10. Create a three dimensional array



In [21]:
arr3di = np.arange(30).reshape(3,2,5)
arr3di

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [26]:
arr1d = np.arange(5)
arr1d #produces [0,1,2,3,4]
arr1d[::-1]

array([4, 3, 2, 1, 0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [31]:
null_vector = np.zeros(10,dtype="int32")
null_vector
null_vector[4] = 1

In [32]:
null_vector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

13. Create a 3x3 identity matrix

In [35]:
np.identity(3,dtype='int32')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [36]:
arr = np.array([1, 2, 3, 4, 5]) 
arr

array([1, 2, 3, 4, 5])

In [37]:
arr.astype(np.float)

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [38]:
arr1 = np.array([[1., 2., 3.],
            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],
           [7., 2., 12.]])

In [39]:
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [6]:
arr_one = np.array([[1., 2., 3.],
            [4., 5., 6.]]) 
arr_two = np.array([[0., 4., 1.], 
            [7., 2., 12.]])

In [8]:
result = arr_one == arr_two
result

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [13]:
an_array = np.arange(10)
print(an_array)
an_array[an_array%2 == 1]

[0 1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [14]:
an_array[an_array%2 == 1] = -1

In [15]:
an_array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [16]:
arr4 = np.arange(10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr4[5:9] = 12

In [18]:
arr4

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [24]:
x = np.ones((5,5),dtype='int32')
x[1:-1,1:-1] = 0

In [25]:
x

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [29]:
arr_2D = np.array([[1, 2, 3],
                    [4, 5, 6], 
                    [7, 8, 9]])
arr_2D[1,1]=12

In [30]:
arr_2D

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [33]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr_3d[0]=64

In [34]:
arr_3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [43]:
arr2dime = np.arange(10).reshape(2,5)
arr2dime

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
arr2dime[0]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [40]:
arr2dim = np.arange(10).reshape(5,2)
arr2dim

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [41]:
arr2dim[1,1]

3

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [39]:
array_2D = np.arange(10).reshape(2,5)
print(array_2D)
array_2D[:,2:3]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [40]:
rand_array = np.random.random((10,10))
rand_array

array([[0.85853106, 0.56725875, 0.04201982, 0.52555901, 0.03971469,
        0.1749425 , 0.08524028, 0.9155827 , 0.69057044, 0.36832847],
       [0.51076671, 0.19929933, 0.63167784, 0.46941586, 0.98851305,
        0.98278863, 0.48262803, 0.62496998, 0.0684647 , 0.20037241],
       [0.52962018, 0.8608553 , 0.80273287, 0.93915822, 0.17708504,
        0.33409655, 0.81039797, 0.62668063, 0.05038309, 0.835764  ],
       [0.11115649, 0.18179973, 0.07161292, 0.10869683, 0.33471175,
        0.25128203, 0.54516044, 0.23235309, 0.7892814 , 0.13033728],
       [0.57530502, 0.05666007, 0.61558675, 0.90087143, 0.20062265,
        0.05570071, 0.63267378, 0.57764011, 0.75763157, 0.99100467],
       [0.45984886, 0.80977902, 0.40010338, 0.51646913, 0.57136109,
        0.08634807, 0.56548489, 0.53922806, 0.18205474, 0.94261678],
       [0.78468835, 0.12541595, 0.45353042, 0.98995651, 0.56611957,
        0.84694282, 0.35675574, 0.18485702, 0.69682064, 0.72283031],
       [0.92123027, 0.42461251, 0.5908705

In [41]:
rand_array.min()

0.03971468687698965

In [42]:
rand_array.max()

0.9910046687786904

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [44]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [45]:
common_items = np.intersect1d(a,b)
common_items

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [46]:
a1 = np.array([1,2,3,2,3,4,3,4,5,6]) 
b1= np.array([7,2,10,2,7,4,9,4,9,8])

In [49]:
np.intersect1d(a1,b1)

array([2, 4])

In [47]:
np.searchsorted(a1, np.intersect1d(a1, b1))

array([1, 5], dtype=int64)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [230]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

In [231]:
data

array([[-1.72216082, -0.19060497,  1.05150816, -1.83654025],
       [-2.1467693 ,  0.65165092,  0.22333219,  0.72233672],
       [ 0.54366033, -0.30965843, -0.41518627, -1.01678245],
       [ 0.6472979 , -0.98353832, -1.56049165,  0.17392728],
       [-0.68905438,  0.29179734,  0.15507137,  0.68587015],
       [-0.27829172,  1.46207851,  0.23250877,  0.97056559],
       [-0.71348448,  1.68006931,  0.96536767, -0.208492  ]])

In [232]:
names_result = np.where(names !='Will')
names_result

(array([0, 1, 3, 5, 6], dtype=int64),)

In [244]:
for x in names_result:
    print(data[x])

[[-1.72216082 -0.19060497  1.05150816 -1.83654025]
 [-2.1467693   0.65165092  0.22333219  0.72233672]
 [ 0.6472979  -0.98353832 -1.56049165  0.17392728]
 [-0.27829172  1.46207851  0.23250877  0.97056559]
 [-0.71348448  1.68006931  0.96536767 -0.208492  ]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [246]:
names1 = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data1 = np.random.randn(7, 4)

In [247]:
names1

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [248]:
data1

array([[ 0.14287056, -0.55477252, -0.75111528,  0.7464727 ],
       [-0.22624842, -0.39430883,  0.51871754,  0.76945959],
       [-0.13876317, -1.30350413,  1.10954149,  2.36928938],
       [ 0.32111006, -0.06672523, -0.9416496 , -0.29803462],
       [ 0.38049353,  0.11649853, -0.53039526, -0.75297846],
       [ 1.99942248, -1.55132412, -1.44879139, -0.2673799 ],
       [-2.63249006, -1.24980185,  0.34011101, -1.00485184]])

In [249]:
names_result1 = np.where((names1 !='Will') & (names1 != 'Joe'))
names_result1

(array([0, 3], dtype=int64),)

In [255]:
for y in names_result1:
    print(data1[y])

[[ 0.14287056 -0.55477252 -0.75111528  0.7464727 ]
 [ 0.32111006 -0.06672523 -0.9416496  -0.29803462]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [75]:
float_array = np.random.uniform(low=1, high=15, size=(5,3))
float_array

array([[ 1.73102366,  6.93803017, 14.49882257],
       [12.18371392,  1.04715002,  2.72106764],
       [12.80839493, 12.03839471,  9.31924166],
       [11.14152396, 14.8819703 ,  7.8388272 ],
       [ 3.38851542,  2.3740021 ,  4.19099176]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [79]:
ar = np.random.uniform(low =1, high=16, size = (2,2,4))
ar

array([[[ 6.69806487,  3.1487191 ,  4.86583849, 13.32060594],
        [15.96797589,  2.62591823,  5.99048983,  9.65570456]],

       [[ 9.27752294, 15.89284909,  9.46562743, 14.08867704],
        [ 2.85752034,  4.65920431, 14.17115604,  9.4149382 ]]])

33. Swap axes of the array you created in Question 32

In [85]:
np.swapaxes(ar,2,0)

array([[[ 6.69806487,  9.27752294],
        [15.96797589,  2.85752034]],

       [[ 3.1487191 , 15.89284909],
        [ 2.62591823,  4.65920431]],

       [[ 4.86583849,  9.46562743],
        [ 5.99048983, 14.17115604]],

       [[13.32060594, 14.08867704],
        [ 9.65570456,  9.4149382 ]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [92]:
arr5= np.arange(10)
print(arr5)


[0 1 2 3 4 5 6 7 8 9]


In [101]:
arr_square_root = np.sqrt(arr5)
print(arr_square_root)


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [102]:
arr_square_root[arr_square_root < 0.5] = 0

In [103]:
arr_square_root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [142]:
arr_random1 = np.random.randint(12,size= (5))
arr_random2 = np.random.randint(12,size= (5))

In [145]:
print(arr_random1)
print(max(arr_random1))

[6 6 8 1 5]
8


In [146]:
print(arr_random2)
print(max(arr_random2))

[4 9 6 1 3]
9


In [148]:
max_values = np.array([max(arr_random1),max(arr_random2)])
max_values

array([8, 9])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [149]:
names2 = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [150]:
np.unique(names2)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [169]:
a4 = np.array([1,2,3,4,5]) 
b4 = np.array([5,6,7,8,9])

In [172]:
common_items_in_both = np.intersect1d(a4,b4)
print(common_items_in_both)
indexof_common_item = np.where(a4==common_items_in_both)
print(indexof_common_item)

[5]
(array([4], dtype=int64),)


In [173]:
new_a4 = np.delete(a4,indexof_common_item)

In [174]:
new_a4

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [199]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 

newColumn = np.array([[10,10,10]])

In [200]:
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [216]:
subarray = np.delete(sampleArray, 1, 1)
subarray

array([[34, 73],
       [82, 12],
       [53, 66]])

In [217]:
new_sampleArray = np.insert(subarray, 1, newColumn, axis=1)
new_sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [218]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [219]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [225]:
matrix = np.random.randint(20,size=(5,4))
matrix

array([[13,  1, 18,  7],
       [ 9, 16, 10, 19],
       [16, 13, 13,  6],
       [ 5, 12, 17,  5],
       [13, 17, 18, 14]])

In [226]:
 matrix.cumsum(axis=0) 

array([[13,  1, 18,  7],
       [22, 17, 28, 26],
       [38, 30, 41, 32],
       [43, 42, 58, 37],
       [56, 59, 76, 51]], dtype=int32)